export const yellow: string = '#efd995'
export const blue: string = '#a6d5e6'
export const darkBlue: string = '#67aec7'
export const black: string = '#171a1b'
export const gray: string = '#ead7d3'
export const white: string = '#f4e2da'
export const darkWhite: string = '#ead7d3'
