export const orange: string = '#D94700'
export const red: string = '#BB1F28'
export const green: string = '#2DC22D'
export const yellow: string = '#FFCF9A'
export const blue: string = '#253a57'
export const black: string = '#2A2C2B'
export const white: string = '#ffffff'
export const transparentWhite: string = 'rgba(255,255,255,.35)'
