name: Tests

on: [push]

jobs:
  tests:
    name: Linting and Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.1
    - name: Install Dependencies
      run: npm ci
    - name: Type checking
      run: npm run check-types
    - name: Style linting
      run: npm run stylelint
