name: Build project and Run Lighthouse CI

on: [push]

jobs:
  tests:
    name: Linting and Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.13.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.1
    - name: Install Dependencies
      run: npm ci
    - name: Type checking
      run: npm run check-types
    - name: Style linting
      run: npm run stylelint

  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: npm install, build
        run: |
          npm ci
          npm run build
      - name: run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: process.env.LHCI_GITHUB_APP_TOKEN
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci'
