name: Build project and Run Lighthouse CI

on: [push]

jobs:
  tests:
    name: Linting and Type Checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Type checking
      run: npm run check-types
    - name: Style linting
      run: npm run stylelint

  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
